
# Site settings
title: Renta de Mesas y Sillas Tiffany
description: Renta de mobiliario y vajilla para eventos en Guadalajara, especializados en sillas tiffany.
url: "https://www.rentatiffany.com" # the base hostname & protocol for your site
enforce_ssl: www.rentatiffany.com
email: info@rentatiffany.com

# Build settings
markdown: kramdown

# or use PAGES_REPO_NWO in the env
repository: joseanu/sillastiffany
gems: ['jekyll-github-metadata', 'jekyll-seo-tag']